module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    // ========== 👥 USER CONTROLLER EVENTS ==========
    BLOCK_USER: "BLOCK_USER",
    UNBLOCK_USER: "UNBLOCK_USER",
    CHECK_AUTH_LOGS: "CHECK_AUTH_LOGS",
    GET_USER_ACTIVE_DEVICES: "GET_USER_ACTIVE_DEVICES",
    PROVIDE_USER_ACCOUNT_DETAILS: "PROVIDE_USER_ACCOUNT_DETAILS",
    GET_TOTAL_REGISTERED_USERS: "GET_TOTAL_REGISTERED_USERS",
    UPDATE_ADMIN_ROLE: "UPDATE_ADMIN_ROLE",
  
    // ========== 👑 ADMIN CONTROLLER EVENTS ==========
    CREATE_ADMIN: "CREATE_ADMIN",
    CREATE_MID_ADMIN: "CREATE_MID_ADMIN",
    ACTIVATE_ADMIN: "ACTIVATE_ADMIN",
    DEACTIVATE_ADMIN: "DEACTIVATE_ADMIN",
    ACTIVATE_MID_ADMIN: "ACTIVATE_MID_ADMIN",
    DEACTIVATE_MID_ADMIN: "DEACTIVATE_MID_ADMIN",
    VIEW_ADMIN_DETAILS: "VIEW_ADMIN_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS",
    UPDATE_MID_ADMIN_DETAILS: "UPDATE_MID_ADMIN_DETAILS",
    UPDATE_OWN_ADMIN_DETAILS: "UPDATE_OWN_ADMIN_DETAILS",
    CHANGE_ADMIN_SUPERVISOR: "CHANGE_ADMIN_SUPERVISOR",
    CHANGE_MID_ADMIN_SUPERVISOR: "CHANGE_MID_ADMIN_SUPERVISOR",
    ROLE_CHANGE_REQUEST_SUBMITTED: "ROLE_CHANGE_REQUEST_SUBMITTED",
    ROLE_CHANGE_REQUEST_APPROVED: "ROLE_CHANGE_REQUEST_APPROVED",
    ROLE_CHANGE_REQUEST_REJECTED: "ROLE_CHANGE_REQUEST_REJECTED",
    
    // ========== 🔄 STATUS REQUEST EVENTS ==========
    CREATE_DEACTIVATION_REQUEST: "CREATE_DEACTIVATION_REQUEST",
    APPROVE_DEACTIVATION_REQUEST: "APPROVE_DEACTIVATION_REQUEST",
    REJECT_DEACTIVATION_REQUEST: "REJECT_DEACTIVATION_REQUEST",
    CREATE_ACTIVATION_REQUEST: "CREATE_ACTIVATION_REQUEST",
    APPROVE_ACTIVATION_REQUEST: "APPROVE_ACTIVATION_REQUEST",
    REJECT_ACTIVATION_REQUEST: "REJECT_ACTIVATION_REQUEST",
    VIEW_ADMIN_REQUEST: "VIEW_ADMIN_REQUEST",
    
    // ========== 📊 ACTIVITY TRACKER EVENTS ==========
    VIEW_ADMIN_ACTIVITY_TRACKER: "VIEW_ADMIN_ACTIVITY_TRACKER",
    LIST_ACTIVITY_TRACKER: "LIST_ACTIVITY_TRACKER",
    BLOCK_USER_DEVICE: "BLOCK_USER_DEVICE",
    UNBLOCK_USER_DEVICE: "UNBLOCK_USER_DEVICE"
  }),

  SERVICE_TRACKER_EVENTS: Object.freeze({
    // ========== 🔧 INTERNAL CONTROLLER EVENTS ==========
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    
    // ========== 🔄 SYNC EVENTS ==========
    SYNC_USER_DATA: "SYNC_USER_DATA", 
    SYNC_ADMIN_DATA: "SYNC_ADMIN_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA",
    
    // ========== 🏗️ SYSTEM EVENTS ==========
    CREATE_SUPER_ADMIN: "CREATE_SUPER_ADMIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  })
};