module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    BLOCK_USER: "BLOCK_USER",
    UNBLOCK_USER: "UNBLOCK_USER",
    CHECK_AUTH_LOGS: "CHECK_AUTH_LOGS",
    GET_USER_ACTIVE_DEVICES: "GET_USER_ACTIVE_DEVICES",
    PROVIDE_USER_ACCOUNT_DETAILS: "PROVIDE_USER_ACCOUNT_DETAILS",
    GET_TOTAL_REGISTERED_USERS: "GET_TOTAL_REGISTERED_USERS",
    CREATE_MID_ADMIN: "CREATE_MID_ADMIN",
    CREATE_ADMIN: "CREATE_ADMIN",
    DEACTIVATE_MID_ADMIN: "DEACTIVATE_MID_ADMIN",
    ACTIVATE_MID_ADMIN: "ACTIVATE_MID_ADMIN",
    ACTIVATE_ADMIN: "ACTIVATE_ADMIN",
    DEACTIVATE_ADMIN: "DEACTIVATE_ADMIN",
    ROLE_CHANGE_REQUEST_SUBMITTED: "ROLE_CHANGE_REQUEST_SUBMITTED",
    ROLE_CHANGE_REQUEST_APPROVED: "ROLE_CHANGE_REQUEST_APPROVED",
    ROLE_CHANGE_REQUEST_REJECTED: "ROLE_CHANGE_REQUEST_REJECTED",
    VIEW_ADMIN_DETAILS: "VIEW_ADMIN_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  }),

  SERVICE_TRACKER_ACTIONS: Object.freeze({
    CLEAN_UP_ACTIVITY_LOGS: "CLEAN_UP_ACTIVITY_LOGS",
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    SYNC_USER_DATA: "SYNC_USER_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA"
  })
};
