module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    BLOCKED: "BLOCKED",
    UNBLOCKED: "UNBLOCKED",
    CHECK_AUTH_LOGS: "CHECK_AUTH_LOGS",
    GET_USER_ACTIVE_DEVICES: "GET_USER_ACTIVE_DEVICES",
    PROVIDE_USER_ACCOUNT_DETAILS: "PROVIDE_USER_ACCOUNT_DETAILS",
    GET_TOTAL_REGISTERED_USERS: "GET_TOTAL_REGISTERED_USERS",
    CLEAN_UP_AUTH_LOGS: "CLEAN_UP_AUTH_LOGS"
  })
};
