module.exports = Object.freeze([
  "BLOCKED",
  "UNBLOCKED",
  "CHECK_AUTH_LOGS",
  "GET_USER_ACTIVE_DEVICES",
  "PROVIDE_USER_ACCOUNT_DETAILS",
  "GET_TOTAL_REGISTERED_USERS",
  "CLEAN_UP_AUTH_LOGS"
]);